# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - berne

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://berne.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_11a65cbc87984c6da699c654d935de23 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d8451f1c20e642028a0a034ca865a71d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: berne.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_11a65cbc87984c6da699c654d935de23 }}/demo:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'berne'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_25d2034a04f644408607fbb5a3fc2e2d }}
        images: 'berne.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_11a65cbc87984c6da699c654d935de23 }}/demo:${{ github.sha }}'